### PR TITLE
X86: support x86 (i386) and x86_64

### PR DESCRIPTION
**Pull request by phip1611**
Hi! I'm developing for a x86 target and the library doesn't work there. I tested the change locally and it works fine. 

Is there any reason for that restriction in the first place?

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
Thanks, looks fine!

**Comment by phip1611** [comment]
Nice, thanks! Do you plan to release it soon? Shall I wait or just reference the git repository in my project?

**Comment by phip1611** [comment]
@adamgreig hi Adam! According to my knowledge, Andre contacted you that I'm interested in helping out as a maintainer. So, how do we want to continue here?

**Comment by adamgreig** [comment]
@phip1611 I'm so sorry for the wait, this PR thread totally dropped off my radar. I've published 3.0.2 with your PR.

We would love help maintaining this crate. Right now it's part of the embedded Rust working group, but it's not clear which team maintains it; ideally to help maintain you'd join one of the working group teams. I'll raise the issue at our meeting next week and see if there's a team we can move the crate to.

**Pull request merged**
